#!/bin/bash

Introducing myself...
    
    First of all tnking u for giving this oppurtunity to introduce myself..
    My name is pooji..I'm 23 years old..

    welcome to hellowold!!
    Happy to learnt...
