# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: push
env:
  java-version: 17
  maven-version: 3.9.4

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.java-version }}
        distribution: 'microsoft'
        cache: maven
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.10.0
      with:
        java-version: ${{ env.java-version }}
        maven-version: ${{ env.maven-version }}
    - run: mvn --version
    - name: Build with Maven
      run: mvn -B package --file pom.xml
